### PR TITLE
Update Raven routing VIC nc files

### PR DESCRIPTION
**Pull request by cjauvin**
In the context of the Raven routing emulator:
* Add `VIC_temperatures.nc`
* Modify the spatial dims of `VIC_streaminputs.nc` from `lon/lat` to `lon_dim/lat_dim` in order to prevent an xarray error where it complains about a clash between the dim names and the var names (which are 2d)

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@cjauvin Is there an issue opened that shows this lon/lat error in action?

**Comment by cjauvin** [comment]
```MissingDimensionsError: 'lon' has more than 1-dimension and the same name as one of its dimensions ('lat', 'lon'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.```

**Comment by cjauvin** [comment]
```
netcdf VIC_streaminputs {
dimensions:
        lon = 10 ;
        lat = 10 ;
        time = 16072 ;
        nv = 2 ;
variables:
        float time(time) ;
                time:standard_name = "time" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "proleptic_gregorian" ;
                time:bounds = "time_bnds" ;
        float time_bnds(time, nv) ;
                time_bnds:standard_name = "time_bounds" ;
                time_bnds:units = "days since 0001-01-01 00:00:00" ;
                time_bnds:calendar = "proleptic_gregorian" ;
        float lon(lat, lon) ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:standard_name = "longitude" ;
        float lat(lat, lon) ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:standard_name = "latitude" ;
        float Streaminputs(time, lat, lon) ;
                Streaminputs:long_name = "total runoff" ;
                Streaminputs:units = "mm" ;
                Streaminputs:description = "combined surface runoff and recharge" ;
                Streaminputs:cell_methods = "time: sum" ;

// global attributes:
                :title = "VIC History File" ;
                :source = "VIC Image Driver" ;
                :history = "Created by hongren on Hongrens-MacBook-Pro.local on Sat Oct 24 18:28:06 2020\n" ;
                :references = "Primary Historical Reference for VIC: Liang, X., D. P. Lettenmaier, E. F. Wood, and S. J. Burges, 1994: A Simple hydrologically Based Model of Land Surface Water and Energy Fluxes for GSMs, J. Geophys. Res., 99(D7), 14,415-14,428." ;
                :comment = "Output from the Variable Infiltration Capacity (VIC) Macroscale Hydrologic Model" ;
                :Conventions = "CF-1.6" ;
                :netcdf_lib_version = "4.7.3 of May  9 2020 10:22:11 $" ;
                :mpi_lib_version = "Open MPI v4.0.3, package: Open MPI brew@Catalina Distribution, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020" ;
                :VIC_Model_Version = "5.0.1 February 1, 2017" ;
                :VIC_GIT_VERSION = "unset" ;
                :VIC_Driver = "Image" ;
}```

**Comment by cjauvin** [comment]
Apparently this will be a problem eventually because it is the standard schema of VIC hydrological model files.

**Comment by huard** [comment]
Not a big problem, because the plan is for Raven to create those streamflows files itself, so we'll control input's conventions. This file is only useful in the interim for testing.

**Review by huard — APPROVED** [review]

**Review by Zeitsperre — APPROVED** [review]

**Pull request merged**
